In [12]:
import pandas as pd
import numpy as np

In [25]:
arr = np.random.randn(10, 8)

m = np.matrix(arr)   
m = m-np.mean(m,axis=0)   #每列去均值 
cov = np.cov(m,rowvar=0)   #计算每两列之间的协方差
# print np.linalg.eig(m)
e,v= np.linalg.eig(cov)
sortede = np.sort(e)
# print e
# print sortede
sortedindex = np.argsort(e)  #特征值从小到大排序后的index 
print sortedindex 
sortedindex = sortedindex[:-5:-1]   # 我只取最大的4个特征值的id
newv = v[:,sortedindex]   #取最大4个特征值对应的特征向量
# print newv
print m*newv   #PCA降维后的数据  


[ 3.06605533  1.70744748  1.03914395  0.00523248  0.09423799  0.47243744
  0.25531389  0.35962724]
[ 0.00523248  0.09423799  0.25531389  0.35962724  0.47243744  1.03914395
  1.70744748  3.06605533]
[3 4 6 7 5 2 1 0]
[[ 1.12079918  1.11362517 -0.18861185  0.31775285]
 [ 1.9864402   0.29419575  2.34520492  0.13983066]
 [ 1.17864301  0.23472637 -0.68914808  0.59235244]
 [ 0.22064404 -1.34092609 -0.59850769 -1.29103677]
 [-0.94324356  1.14777609 -1.31899287  0.5209657 ]
 [ 0.9156826  -2.36191111 -0.17813629  0.23964865]
 [ 0.94893643  1.68043216 -0.29880664 -1.1699929 ]
 [-0.1762288   0.28376055 -0.09637104  0.55405678]
 [-1.12504939 -1.48337153 -0.03141206  0.27669809]
 [-4.12662371  0.43169265  1.05478161 -0.18027551]]
